apiVersion: secrets.oleksiyp.dev/v1alpha1
kind: DerivedSecret
metadata:
  name: {{ .Release.Namespace }}-derived
  namespace: secrets
spec:
  type: Opaque
  keys:
    exampleMicroserviceDbUserPassword:
      type: password  # 26 chars by default
      masterPassword: default
    exampleMicroserviceDbOwnerUserPassword:
      type: password  # 26 chars by default
      masterPassword: default
    jwtSecret:
      type: encryption-key  # 48 chars by default
      masterPassword: default
