apiVersion: secrets.oleksiyp.dev/v1alpha1
kind: DerivedSecret
metadata:
  name: metabase-derived
  namespace: secrets
spec:
  type: Opaque
  keys:
    adminPassword:
      type: password  # 26 chars by default
      masterPassword: default
